version: "3.0"

services:
  api:
    container_name: fastapi-test
    build: .
    volumes:
      - type: bind
        source: ./app
        target: /workspace/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    # コマンドで指定して、サーバーを起動しているが、アクセスできない
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
